set_property PROHIBIT true [get_bels IPAD_X0Y1/PAD]
set_property PROHIBIT true [get_bels IPAD_X0Y0/PAD]
set_property PROHIBIT true [get_sites K9]
set_property PROHIBIT true [get_sites J10]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN N5 [get_ports rxd]
set_property IOSTANDARD LVCMOS33 [get_ports rxd]
set_property IOSTANDARD LVCMOS33 [get_ports txd]
set_property PACKAGE_PIN T4 [get_ports txd]

set_property MARK_DEBUG true [get_nets rxd_IBUF]
set_property MARK_DEBUG true [get_nets clk_uart]
set_property MARK_DEBUG true [get_nets {data_i[0]}]
set_property MARK_DEBUG true [get_nets {data_i[1]}]
set_property MARK_DEBUG true [get_nets {data_i[2]}]
set_property MARK_DEBUG true [get_nets {data_i[3]}]
set_property MARK_DEBUG true [get_nets {data_i[4]}]
set_property MARK_DEBUG true [get_nets {data_i[5]}]
set_property MARK_DEBUG true [get_nets {data_i[6]}]
set_property MARK_DEBUG true [get_nets {data_i[7]}]
set_property MARK_DEBUG true [get_nets {uart_rx1/nxt_st[0]}]
set_property MARK_DEBUG true [get_nets {uart_rx1/nxt_st[1]}]
set_property MARK_DEBUG true [get_nets clk_IBUF]
set_property MARK_DEBUG true [get_nets {cur_st[0]}]
set_property MARK_DEBUG true [get_nets {cur_st[1]}]
connect_debug_port u_ila_0/probe4 [get_nets [list {uart_rx1/nxt_st[0]} {uart_rx1/nxt_st[1]}]]

set_property MARK_DEBUG true [get_nets {uart_rx1/rx_cur_st[0]}]
set_property MARK_DEBUG true [get_nets {uart_rx1/rx_cur_st[1]}]
set_property MARK_DEBUG true [get_nets {uart_rx1/count[0]}]
set_property MARK_DEBUG true [get_nets {uart_rx1/count[1]}]
set_property MARK_DEBUG true [get_nets {uart_rx1/count[2]}]
set_property MARK_DEBUG false [get_nets {uart_rx1/count[0]_i_1_n_0}]
set_property MARK_DEBUG false [get_nets {uart_rx1/count[1]_i_1_n_0}]
set_property MARK_DEBUG false [get_nets {uart_rx1/count[2]_i_1_n_0}]



set_property OFFCHIP_TERM NONE [get_ports txd]
